"""Report generation for the read-only Sunhaven integration layer."""

from __future__ import annotations

import csv
import html
import json
from pathlib import Path
from typing import Any


def write_integration_json(snapshot: dict[str, Any], leaver_result: dict[str, Any], output_path):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "snapshot": snapshot,
        "integratedLeaverAnalysis": leaver_result,
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def write_rbac_matrix_csv(snapshot: dict[str, Any], output_path):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["role", "route", "purpose", "allowed", "unauthorized_result"]

    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in snapshot["authorization"]["rbacMatrix"]:
            writer.writerow(
                {
                    "role": row["role"],
                    "route": row["route"],
                    "purpose": row["purpose"],
                    "allowed": row["allowed"],
                    "unauthorized_result": row["unauthorizedResult"],
                }
            )
    return path


def _yes_no(value):
    return "Yes" if value else "No"


def write_integration_html(
    snapshot: dict[str, Any],
    leaver_result: dict[str, Any],
    output_path,
    title="Sunhaven SITAS Integrated Security Analysis",
):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    source_rows = []
    for name, item in snapshot["sourceInventory"].items():
        source_rows.append(
            "<tr>"
            f"<td>{html.escape(name)}</td>"
            f"<td>{html.escape(item['path'])}</td>"
            f"<td>{_yes_no(item['present'])}</td>"
            "</tr>"
        )

    workforce_rows = []
    for worker in snapshot["workforce"]["leavingWorkers"]:
        workforce_rows.append(
            "<tr>"
            f"<td>{html.escape(worker['employeeId'])}</td>"
            f"<td>{html.escape(worker['jobRole'])}</td>"
            f"<td>{html.escape(worker['facility'])}</td>"
            f"<td>{html.escape(worker['status'])}</td>"
            f"<td>{html.escape(worker['endDate'] or '-')}</td>"
            "</tr>"
        )

    rbac_rows = []
    for row in snapshot["authorization"]["rbacMatrix"]:
        rbac_rows.append(
            "<tr>"
            f"<td>{html.escape(row['role'])}</td>"
            f"<td>{html.escape(row['route'])}</td>"
            f"<td>{'ALLOW' if row['allowed'] else 'DENY'}</td>"
            f"<td>{html.escape(row['unauthorizedResult'])}</td>"
            "</tr>"
        )

    control_rows = []
    for control in snapshot["controlMappings"]:
        control_rows.append(
            "<tr>"
            f"<td>{html.escape(control['controlId'])}</td>"
            f"<td>{html.escape(control['sunhavenArea'])}</td>"
            f"<td>{html.escape(control['integrationStatus'])}</td>"
            f"<td>{html.escape(control['note'])}</td>"
            "</tr>"
        )

    findings_html = "<p>No configuration warnings found in the analysed files.</p>"
    if snapshot["findings"]:
        items = []
        for finding in snapshot["findings"]:
            values = ", ".join(str(value) for value in finding.get("values", []))
            suffix = f" ({html.escape(values)})" if values else ""
            items.append(
                f"<li><strong>{html.escape(finding['id'])}</strong>: "
                f"{html.escape(finding['message'])}{suffix}</li>"
            )
        findings_html = "<ul>" + "".join(items) + "</ul>"

    comparison = leaver_result["comparison"]
    integration = leaver_result["integration"]
    observed = integration["observedEvidence"]
    baseline_path = " → ".join(leaver_result["baseline"].get("pathNodeNames", []))

    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 2rem; line-height: 1.45; max-width: 1200px; }}
h1, h2 {{ margin-bottom: .45rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }}
th, td {{ border: 1px solid #aaa; padding: .5rem; text-align: left; vertical-align: top; }}
th {{ font-weight: 700; }}
.notice {{ border: 1px solid #888; padding: .8rem; }}
code {{ font-family: Consolas, monospace; }}
</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<p class="notice"><strong>Scope:</strong> This report is generated by a read-only adapter. It analyses Sunhaven project files and optional sanitised evidence. It does not query or modify live Microsoft Entra ID, execute JML automation, change Flask state, or claim that a simulated control is live enforcement.</p>

<h2>Integration sources</h2>
<table><thead><tr><th>Source</th><th>Project path</th><th>Present</th></tr></thead>
<tbody>{''.join(source_rows)}</tbody></table>

<h2>Workforce snapshot</h2>
<p>Records: <strong>{snapshot['workforce']['recordCount']}</strong> | Roles: {html.escape(', '.join(snapshot['workforce']['roles']))} | Facilities: {html.escape(', '.join(snapshot['workforce']['facilities']))}</p>
<table><thead><tr><th>Employee ID</th><th>Role</th><th>Facility</th><th>Status</th><th>End date</th></tr></thead>
<tbody>{''.join(workforce_rows) or '<tr><td colspan="5">No Leaving/Inactive record found.</td></tr>'}</tbody></table>

<h2>Integrated former-worker analysis</h2>
<p><strong>Selected employee:</strong> {html.escape(integration['employeeId'])} ({html.escape(integration['jobRole'])}, {html.escape(integration['workforceStatus'])})</p>
<p><strong>Source:</strong> <code>{html.escape(integration['sourceFile'])}</code></p>
<p><strong>Baseline path:</strong> {html.escape(baseline_path)}</p>
<p><strong>Control OFF:</strong> {html.escape(comparison['baselineStatus'])}</p>
<p><strong>Control ON:</strong> {html.escape(comparison['protectedStatus'])}</p>
<p><strong>Path interrupted:</strong> {_yes_no(comparison['pathInterrupted'])}</p>
<p><strong>Operational-evidence assessment:</strong> {html.escape(observed['assessment'])}</p>

<h2>RBAC configuration matrix</h2>
<p>This matrix is derived directly from <code>config/route-role-map.csv</code> and the configured app roles.</p>
<table><thead><tr><th>Role</th><th>Route</th><th>Configured result</th><th>Unauthorised result</th></tr></thead>
<tbody>{''.join(rbac_rows)}</tbody></table>

<h2>SITAS-to-Sunhaven control mapping</h2>
<table><thead><tr><th>SITAS control</th><th>Sunhaven area</th><th>Status</th><th>Boundary note</th></tr></thead>
<tbody>{''.join(control_rows)}</tbody></table>

<h2>Integration validation findings</h2>
{findings_html}
</body>
</html>
"""

    path.write_text(document, encoding="utf-8")
    return path
